spring:
  datasource:
    url: jdbc:sqlserver://localhost\MSSQLSERVER:1433;database=unfv_sistema_inventarios_prod;integratedSecurity=false;encrypt=true;trustServerCertificate=true;
    username: sa
    password: admin
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: sql_server